In [1]:
import numpy as np
import pandas as pd
import grey_functions as gf
from IPython.display import display

len_min = 3
len_max = 7

col_sdr = 'Source data range'
col_pv = '№ predict value'
col_tv = 'True value'
col_gm = 'GM'
col_mgm = 'MGM'
col_regm = 'error GM,%'
col_remgm = 'error MGM,%'

# read from input.txt file
data = np.loadtxt("input.txt", delimiter=' ', dtype=np.float)

In [5]:
# N - кол-во исходных данных
# k - текущая длина промежутка для построения модели
# len_min, len_max - минимальная и максимальная длина промежутка

error_MGM = []
error_GM  = []

dfs = []
for k in range(len_min, len_max+1):
    print("k =", k,end=" ")
    order = []
    predict_mgm = []
    predict_gm = gf.grey_method_prediction(data[len_max-k:len_max], len(data)-len_max+k)[k-1:]
    index_value = [x for x in range(len_max+1, len(data)+1)]
    true_value = data[len_max:len(data)]
    for i in range(len(data)-len_max):
        order.append(str(len_max+1-k+i)+"-"+str(len_max+i))
        predict_mgm.append(gf.metabolic_grey_method_prediction(data[len_max-k+i:len_max+i],1)[0][2])
    df = pd.DataFrame({
        col_sdr: order,
        col_pv: index_value,
        col_tv: true_value,
        col_mgm: np.round(predict_mgm,3),col_remgm: np.round(np.abs(predict_mgm - true_value)/true_value*100,2),
        col_gm : np.round(predict_gm,3), col_regm: np.round(np.abs(predict_gm - true_value)/true_value*100,2)
    })
    error_MGM.append([np.round(df[col_remgm].mean(),3),k])
    error_GM.append([np.round(df[col_regm].mean(),3),k])
    display(df)
    print('Средняя относительная ошибка MGM:',np.round(df[col_remgm].mean(),3))
    print('Средняя относительная ошибка GM:', np.round(df[col_regm].mean(), 3))
    print()

error_MGM.sort()
error_GM.sort()

print("С",error_GM[0][1],"значениями у GM лучший результат со средней ошибкой",error_GM[0][0])
print("С",error_MGM[0][1],"значениями у MGM лучший результат со средней ошибкой",error_MGM[0][0])

print("\n\nВведите какую модель использовать, с каким кол-вом значений и период прогноза")

model, n, p = input("(mgm/gm) (1-{0}) (1-{1}): ".format(len(data),len(data)-1)).split()
n, p = int(n), int(p) 
while (model != ('mgm' or 'gm') or ((1 > n) and (n > len(data))) or ((1 > p) and (p > len(data)-1))):
    model, n, p = input("(mgm/gm) (1-{0}) (1-{1}): ".format(len(data),len(data)-1)).split()
    n, p = int(n), int(p)
if model == 'mgm':
    t = gf.metabolic_grey_method_prediction(data[len(data)-n:],p)
elif model == 'gm':
    t = gf.grey_method_prediction(data[len(data)-n:],p)
else:
    print("Error....")
for i in t:
    print (i)



k = 3 

Source data range  № predict value  True value      MGM  error MGM,%  \
0                5-7                8     240.032  227.689         5.14   
1                6-8                9     259.271  262.509         1.25   
2                7-9               10     280.832  279.887         0.34   
3               8-10               11     290.382  303.992         4.69   
4               9-11               12     304.628  300.226         1.44   
5              10-12               13     329.988  319.505         3.18   
6              11-13               14     352.782  357.231         1.26   
7              12-14               15     387.544  376.987         2.72   
8              13-15               16     395.273  425.345         7.61   
9              14-16               17     405.644  403.142         0.62   
10             15-17               18     423.967  416.262         1.82   

         GM  error GM,%  
0   227.689        5.14  
1   236.432        8.81  
2   245.510       12.58  
3   254.937       12.21  
4   264.726       13.10  
5   274.891       16.70  
6   285.446       19.09  
7   296.406       23.52  
8   307.787       22.13  
9   319.605       21.21  
10  331.877       21.72

Средняя относительная ошибка MGM: 2.734
Средняя относительная ошибка GM: 16.019

k = 4 

Source data range  № predict value  True value      MGM  error MGM,%  \
0                4-7                8     240.032  235.292         1.97   
1                5-8                9     259.271  254.129         1.98   
2                6-9               10     280.832  282.125         0.46   
3               7-10               11     290.382  303.466         4.51   
4               8-11               12     304.628  309.093         1.47   
5               9-12               13     329.988  316.582         4.06   
6              10-13               14     352.782  350.224         0.73   
7              11-14               15     387.544  380.029         1.94   
8              12-15               16     395.273  418.387         5.85   
9              13-16               17     405.644  422.389         4.13   
10             14-17               18     423.967  414.603         2.21   

         GM  error GM,%  
0   235.292        1.97  
1   250.583        3.35  
2   266.867        4.97  
3   284.209        2.13  
4   302.679        0.64  
5   322.349        2.32  
6   343.297        2.69  
7   365.606        5.66  
8   389.365        1.49  
9   414.668        2.22  
10  441.616        4.16

Средняя относительная ошибка MGM: 2.665
Средняя относительная ошибка GM: 2.873

k = 5 

Source data range  № predict value  True value      MGM  error MGM,%  \
0                3-7                8     240.032  236.204         1.59   
1                4-8                9     259.271  255.833         1.33   
2                5-9               10     280.832  276.960         1.38   
3               6-10               11     290.382  304.887         5.00   
4               7-11               12     304.628  313.139         2.79   
5               8-12               13     329.988  321.796         2.48   
6               9-13               14     352.782  344.446         2.36   
7              10-14               15     387.544  376.318         2.90   
8              11-15               16     395.273  417.232         5.56   
9              12-16               17     405.644  427.049         5.28   
10             13-17               18     423.967  428.079         0.97   

         GM  error GM,%  
0   236.204        1.59  
1   252.173        2.74  
2   269.222        4.13  
3   287.422        1.02  
4   306.854        0.73  
5   327.599        0.72  
6   349.746        0.86  
7   373.391        3.65  
8   398.635        0.85  
9   425.585        4.92  
10  454.357        7.17

Средняя относительная ошибка MGM: 2.876
Средняя относительная ошибка GM: 2.58

k = 6 

Source data range  № predict value  True value      MGM  error MGM,%  \
0                2-7                8     240.032  234.958         2.11   
1                3-8                9     259.271  255.649         1.40   
2                4-9               10     280.832  277.320         1.25   
3               5-10               11     290.382  301.038         3.67   
4               6-11               12     304.628  316.803         4.00   
5               7-12               13     329.988  325.893         1.24   
6               8-13               14     352.782  346.000         1.92   
7               9-14               15     387.544  371.177         4.22   
8              10-15               16     395.273  412.747         4.42   
9              11-16               17     405.644  430.660         6.17   
10             12-17               18     423.967  434.949         2.59   

         GM  error GM,%  
0   234.958        2.11  
1   250.135        3.52  
2   266.294        5.18  
3   283.496        2.37  
4   301.809        0.93  
5   321.305        2.63  
6   342.061        3.04  
7   364.157        6.03  
8   387.681        1.92  
9   412.725        1.75  
10  439.386        3.64

Средняя относительная ошибка MGM: 2.999
Средняя относительная ошибка GM: 3.011

k = 7 

Source data range  № predict value  True value      MGM  error MGM,%  \
0                1-7                8     240.032  233.334         2.79   
1                2-8                9     259.271  254.101         1.99   
2                3-9               10     280.832  276.724         1.46   
3               4-10               11     290.382  300.839         3.60   
4               5-11               12     304.628  315.564         3.59   
5               6-12               13     329.988  330.019         0.01   
6               7-13               14     352.782  348.387         1.25   
7               8-14               15     387.544  371.369         4.17   
8               9-15               16     395.273  406.887         2.94   
9              10-16               17     405.644  429.897         5.98   
10             11-17               18     423.967  440.624         3.93   

         GM  error GM,%  
0   233.334        2.79  
1   247.610        4.50  
2   262.759        6.44  
3   278.835        3.98  
4   295.895        2.87  
5   313.998        4.85  
6   333.209        5.55  
7   353.596        8.76  
8   375.229        5.07  
9   398.187        1.84  
10  422.549        0.33

Средняя относительная ошибка MGM: 2.883
Средняя относительная ошибка GM: 4.271

С 5 значениями у GM лучший результат со средней ошибкой 2.58
С 4 значениями у MGM лучший результат со средней ошибкой 2.665


Введите какую модель использовать, с каким кол-вом значений и период прогноза
(mgm/gm) (1-18) (1-17): mgm 5 10
[-2.98000000e-02  3.68979100e+02  4.34040959e+02]
[-3.24000000e-02  3.75786800e+02  4.49439934e+02]
[-3.30000000e-02  3.87572200e+02  4.64719911e+02]
[-3.11000000e-02  4.03356000e+02  4.78575921e+02]
[-3.26000000e-02  4.13740600e+02  4.95064064e+02]
[-3.19000000e-02  4.28530300e+02  5.10817734e+02]
[-3.18000000e-02  4.42651300e+02  5.27211228e+02]
[-3.21000000e-02  4.56308000e+02  5.44588562e+02]
[-3.1800000e-02  4.7186230e+02  5.6195738e+02]
[-3.19000000e-02  4.86885800e+02  5.80176076e+02]
